export default interface ISkillSystem {
    trainee: string,
    beginner: string,
    intermediate: string,
    advanced: string,
    expert: string,
    preference: string,
    loveIt: string,
    years: string,
    current: string,
    last: string,
    projects: string,
    frequency: string,
    related: string,
    certifications: string,
    learning: string,
    experience: string,
}